import Head from "next/head";
import Navbar from "@/components/Navbar";
import AnnouncementBar from "@/components/AnnouncementBar";
import Hero from "@/components/Hero";
import MarqueeCards from "@/components/MarqueeCards";

export default function Home() {
  return (
    <>
      <Head>
        <link
          rel="icon"
          type="image/png"
          href="//bravaland.com/cdn/shop/files/2_brava_favicon_XXL.png?crop=center&height=32&v=1684747310&width=32"
        />

        <title>brava | Shop NFT Apparel, Art, Accessories, &amp; Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="main">
        <AnnouncementBar />
        <Navbar />
        <Hero />
        <MarqueeCards />
      </main>
    </>
  );
}
